### ISSUE TITLE
load.sh have a error

### ISSUE THREAD

**Issue by fslq123** [AppleIntelWifi/adapter#52] opened 2020-04-17 10:53 UTC
**Describe the bug**
./scripts/load.sh: line 10: .unload.sh: command not found

**How to reproduce**
./scripts/build.sh && ./scripts/load.sh

**Deal with methods**

1.Edit load.sh
2.Change '(.unload.sh | true)' to '(./scripts/unload.sh | true)

**Comment by fslq123** [comment] 2020-04-17 10:59
And when I make the code 'sudo kextload -v AppleIntelWifiAdapterV2.kext' ,It appears an error that 'Requesting load of /Users/fslq/Downloads/AppleIntelWifiV2/AppleIntelWifiAdapterV2.kext.
/Users/fslq/Downloads/AppleIntelWifiV2/AppleIntelWifiAdapterV2.kext failed to load - (libkern/kext) link error; check the system/kernel logs for errors or try kextutil(8).'
What should I do? And my OS is 10.15.4,8265AC.

**Comment by williambj1** [comment] 2020-04-17 10:59
It's because you're launching the script in a wrong Dir, cd into the `scripts` folder first.

I think it's better to use `PWD` and `dirname` to solve this.

**Comment by fslq123** [comment] 2020-04-17 11:02
Ok,enn, the first issue reason I know.

**Comment by tvhung83** [comment] 2020-04-17 11:02
> It's because you're launching the script in a wrong Dir, cd into the scripts folder first.

Check README, it's saying to run `./scripts/build.sh && ./scripts/load.sh`, ie. you have to be at root project dir. Anyway, it's not a big deal, but I'd rather print something before I expect key input.

**Comment by tvhung83** [comment] 2020-04-17 11:04
> And when I make the code 'sudo kextload -v AppleIntelWifiAdapterV2.kext' ,It appears an error that 'Requesting load of /Users/fslq/Downloads/AppleIntelWifiV2/AppleIntelWifiAdapterV2.kext.
/Users/fslq/Downloads/AppleIntelWifiV2/AppleIntelWifiAdapterV2.kext failed to load - (libkern/kext) link error; check the system/kernel logs for errors or try kextutil(8).'
What should I do? And my OS is 10.15.4,8265AC.

It's in top at issue list. Author is aware about it, don't post duplicated issue.

**Comment by rv32ima** [comment] 2020-04-17 11:06
There’s already an env script that’s sourced and pulls the kext from the local build folder. Bypassing that is obviously not a bug, but I can easily fix the unload issue.

**Comment by williambj1** [comment] 2020-04-17 11:07
> > It's because you're launching the script in a wrong Dir, cd into the scripts folder first.
> 
> Check README, it's saying to run `./scripts/build.sh && ./scripts/load.sh`, ie. you have to be at root project dir. Anyway, it's not a big deal, but I'd rather print something before I expect key input.

Oops, I missed that, thanks for pointing out, I usually type in the commands manually LOL.

**Comment by fslq123** [comment] 2020-04-17 11:07
Okey,l ignore this issue, thanks a lot.

**Comment by tvhung83** [comment] 2020-04-17 11:14
@fslq123 please close it to not pollute issue list 🙂

**Comment by fslq123** [comment] 2020-04-17 11:51
okey

**Closed as completed** 2020-04-17 11:50 UTC
Labels: bug
