### ISSUE TITLE
Unable to load due to missing symbols

### ISSUE THREAD

**Issue by bin** [AppleIntelWifi/adapter#54] opened 2020-04-19 03:13 UTC
**Describe the bug**
Kext fails to load on MacOS 10.15.4 due to unresolved symbols.

**How to reproduce**
Download from website or build from source, run `sudo kextload $KEXTNAME`.  Get this error:
```
Kext with invalid signature (-67050) allowed: <OSKext 0x7fc4b3527c60 [0x7fff8ba058c0]> { URL = "file:///Users/bin/code/adapter/build/Build/Products/Debug/AppleIntelWifiAdapterV2.kext/", ID = "com.apple.AppleIntelWifiAdapterV2" }
Code Signing Failure: code signature is invalid
Disabling KextAudit: SIP is off
(kernel) kxld[com.apple.AppleIntelWifiAdapterV2]: The following symbols are unresolved for this kext:
(kernel) kxld[com.apple.AppleIntelWifiAdapterV2]: 	__Z11initTimeoutP10IOWorkLoop
(kernel) kxld[com.apple.AppleIntelWifiAdapterV2]: 	__Z14releaseTimeoutv
(kernel) kxld[com.apple.AppleIntelWifiAdapterV2]: 	__ZN8CTimeout9metaClassE
(kernel) kxld[com.apple.AppleIntelWifiAdapterV2]: 	__ZN8CTimeoutC1Ev
(kernel) kxld[com.apple.AppleIntelWifiAdapterV2]: 	__fCommandGate
(kernel) kxld[com.apple.AppleIntelWifiAdapterV2]: 	__fWorkloop
(kernel) Can't load kext com.apple.AppleIntelWifiAdapterV2 - link failed.
(kernel) Failed to load executable for kext com.apple.AppleIntelWifiAdapterV2.
(kernel) Kext com.apple.AppleIntelWifiAdapterV2 failed to load (0xdc008016).
(kernel) Failed to load kext com.apple.AppleIntelWifiAdapterV2 (error 0xdc008016).
Failed to load /Users/bin/code/adapter/build/Build/Products/Debug/AppleIntelWifiAdapterV2.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).
```

**Expected behavior**
Have the kext load.

**Wireless card name**
Intel 9260

**Comment by averycblack** [comment] 2020-04-19 05:42
This is a known issue
Duplicate of #49 
He's working on it 👍

**Comment by baddles** [comment] 2020-04-19 05:42
Again, known issue #49

**Closed as completed** 2020-04-19 18:57 UTC
Labels: bug, duplicate
