### ISSUE TITLE
Driver fails to start on 10.15.5 Beta (19F62f)

### ISSUE THREAD

**Issue by rdmitry0911** [AppleIntelWifi/adapter#61] opened 2020-04-24 11:39 UTC
**Describe the bug**
Driver failed to start

**How to reproduce**
Download the release version from https://intelwifi.0xcc.pw or you can build from source.

Step 1

❯ sudo kextload $KEXTNAME
Step 2

❯ ./logs.sh
**Result**

ERR: SecBoot CPU1 Status: 0x30d0001, CPU2 Status: 0x2
ERR: timeout. iwl_fw_dbg_error_collect
ERR: Failed to start INIT ucode: -60
ERR: init mvm ucode fail
ERR: Failed to run INIT ucode: -60
CRIT: Driver failed to start
**Expected behavior**
Driver start without errors

**Wireless card name**
Intel(R) Wireless-AC 9560

**Additional context**
LG 17 Gram 17z990 
[iwllog.txt](https://github.com/AppleIntelWifi/adapter/files/4528605/iwllog.txt)

**Comment by rv32ima** [comment] 2020-04-24 18:04
Duplicate of #24

**Closed as completed by rv32ima** 2020-04-24 18:04 UTC
Labels: bug, duplicate
